from __future__ import annotations


DRAFT = "DRAFT"
SUBMITTED = "SUBMITTED"
WAITING_FOR_REVIEW = "WAITING_FOR_REVIEW"
REVIEW_ACCEPTED = "REVIEW_ACCEPTED"
REVIEW_REJECTED = "REVIEW_REJECTED"
WAITING_FOR_CORRECTION = "WAITING_FOR_CORRECTION"
CORRECTED = "CORRECTED"
WAITING_FOR_DOCUMENT = "WAITING_FOR_DOCUMENT"
WAITING_FOR_SIGNATURE = "WAITING_FOR_SIGNATURE"
SIGNATURE_INVALID = "SIGNATURE_INVALID"
COMPLETED = "COMPLETED"
CANCELLED = "CANCELLED"


LEGACY_STATUS_MAP = {
    "FORM_SUBMITTED": SUBMITTED,
    "WAITING_FOR_OFFICER_DECISION": WAITING_FOR_REVIEW,
    "DECLARATION_WAITING_FOR_SIGNATURE": WAITING_FOR_SIGNATURE,
    "AGREEMENT_WAITING_FOR_SIGNATURE": WAITING_FOR_SIGNATURE,
    "DECLARATION_SIGNATURE_INVALID": SIGNATURE_INVALID,
    "AGREEMENT_SIGNATURE_INVALID": SIGNATURE_INVALID,
    "OFFICER_ACCEPTED": REVIEW_ACCEPTED,
    "OFFICER_REJECTED": REVIEW_REJECTED,
    "PARTICIPANT_ACCEPTED": COMPLETED,
    "PROCESS_COMPLETED": COMPLETED,
}


TARGET_STATUSES = {
    DRAFT,
    SUBMITTED,
    WAITING_FOR_REVIEW,
    REVIEW_ACCEPTED,
    REVIEW_REJECTED,
    WAITING_FOR_CORRECTION,
    CORRECTED,
    WAITING_FOR_DOCUMENT,
    WAITING_FOR_SIGNATURE,
    SIGNATURE_INVALID,
    COMPLETED,
    CANCELLED,
}


def normalize_status(status: str | None) -> str:
    value = str(status or "").strip()
    if not value:
        return DRAFT
    if value in TARGET_STATUSES:
        return value
    return LEGACY_STATUS_MAP.get(value, value)
